/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as DmnRouteImport } from "./routes/dmn"
import { Route as BpmnRouteImport } from "./routes/bpmn"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as DeploymentsIndexRouteImport } from "./routes/deployments/index"
import { Route as DefinitionsIndexRouteImport } from "./routes/definitions/index"
import { Route as DeploymentsIdRouteImport } from "./routes/deployments/$id"
import { Route as DefinitionsIdRouteImport } from "./routes/definitions/$id"

const DmnRoute = DmnRouteImport.update({
  id: "/dmn",
  path: "/dmn",
  getParentRoute: () => rootRouteImport,
} as any)
const BpmnRoute = BpmnRouteImport.update({
  id: "/bpmn",
  path: "/bpmn",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: "/deployments/",
  path: "/deployments/",
  getParentRoute: () => rootRouteImport,
} as any)
const DefinitionsIndexRoute = DefinitionsIndexRouteImport.update({
  id: "/definitions/",
  path: "/definitions/",
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIdRoute = DeploymentsIdRouteImport.update({
  id: "/deployments/$id",
  path: "/deployments/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const DefinitionsIdRoute = DefinitionsIdRouteImport.update({
  id: "/definitions/$id",
  path: "/definitions/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/bpmn": typeof BpmnRoute
  "/dmn": typeof DmnRoute
  "/definitions/$id": typeof DefinitionsIdRoute
  "/deployments/$id": typeof DeploymentsIdRoute
  "/definitions/": typeof DefinitionsIndexRoute
  "/deployments/": typeof DeploymentsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/bpmn": typeof BpmnRoute
  "/dmn": typeof DmnRoute
  "/definitions/$id": typeof DefinitionsIdRoute
  "/deployments/$id": typeof DeploymentsIdRoute
  "/definitions": typeof DefinitionsIndexRoute
  "/deployments": typeof DeploymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/bpmn": typeof BpmnRoute
  "/dmn": typeof DmnRoute
  "/definitions/$id": typeof DefinitionsIdRoute
  "/deployments/$id": typeof DeploymentsIdRoute
  "/definitions/": typeof DefinitionsIndexRoute
  "/deployments/": typeof DeploymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/bpmn"
    | "/dmn"
    | "/definitions/$id"
    | "/deployments/$id"
    | "/definitions/"
    | "/deployments/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/bpmn"
    | "/dmn"
    | "/definitions/$id"
    | "/deployments/$id"
    | "/definitions"
    | "/deployments"
  id:
    | "__root__"
    | "/"
    | "/bpmn"
    | "/dmn"
    | "/definitions/$id"
    | "/deployments/$id"
    | "/definitions/"
    | "/deployments/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BpmnRoute: typeof BpmnRoute
  DmnRoute: typeof DmnRoute
  DefinitionsIdRoute: typeof DefinitionsIdRoute
  DeploymentsIdRoute: typeof DeploymentsIdRoute
  DefinitionsIndexRoute: typeof DefinitionsIndexRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dmn": {
      id: "/dmn"
      path: "/dmn"
      fullPath: "/dmn"
      preLoaderRoute: typeof DmnRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bpmn": {
      id: "/bpmn"
      path: "/bpmn"
      fullPath: "/bpmn"
      preLoaderRoute: typeof BpmnRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/deployments/": {
      id: "/deployments/"
      path: "/deployments"
      fullPath: "/deployments/"
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/definitions/": {
      id: "/definitions/"
      path: "/definitions"
      fullPath: "/definitions/"
      preLoaderRoute: typeof DefinitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/deployments/$id": {
      id: "/deployments/$id"
      path: "/deployments/$id"
      fullPath: "/deployments/$id"
      preLoaderRoute: typeof DeploymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/definitions/$id": {
      id: "/definitions/$id"
      path: "/definitions/$id"
      fullPath: "/definitions/$id"
      preLoaderRoute: typeof DefinitionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BpmnRoute: BpmnRoute,
  DmnRoute: DmnRoute,
  DefinitionsIdRoute: DefinitionsIdRoute,
  DeploymentsIdRoute: DeploymentsIdRoute,
  DefinitionsIndexRoute: DefinitionsIndexRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
