/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TenantsRouteImport } from "./routes/tenants"
import { Route as DmnRouteImport } from "./routes/dmn"
import { Route as BpmnRouteImport } from "./routes/bpmn"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TasksIndexRouteImport } from "./routes/tasks/index"
import { Route as JobsIndexRouteImport } from "./routes/jobs/index"
import { Route as InstancesIndexRouteImport } from "./routes/instances/index"
import { Route as IdentityIndexRouteImport } from "./routes/identity/index"
import { Route as HistoryIndexRouteImport } from "./routes/history/index"
import { Route as EventsIndexRouteImport } from "./routes/events/index"
import { Route as DeploymentsIndexRouteImport } from "./routes/deployments/index"
import { Route as DefinitionsIndexRouteImport } from "./routes/definitions/index"
import { Route as DecisionsIndexRouteImport } from "./routes/decisions/index"
import { Route as BatchesIndexRouteImport } from "./routes/batches/index"
import { Route as TasksIdRouteImport } from "./routes/tasks/$id"
import { Route as InstancesIdRouteImport } from "./routes/instances/$id"
import { Route as DeploymentsIdRouteImport } from "./routes/deployments/$id"
import { Route as DefinitionsIdRouteImport } from "./routes/definitions/$id"
import { Route as DecisionsKeyRouteImport } from "./routes/decisions/$key"
import { Route as BatchesIdRouteImport } from "./routes/batches/$id"
import { Route as IdentityUsersIdRouteImport } from "./routes/identity/users/$id"
import { Route as IdentityGroupsIdRouteImport } from "./routes/identity/groups/$id"

const TenantsRoute = TenantsRouteImport.update({
  id: "/tenants",
  path: "/tenants",
  getParentRoute: () => rootRouteImport,
} as any)
const DmnRoute = DmnRouteImport.update({
  id: "/dmn",
  path: "/dmn",
  getParentRoute: () => rootRouteImport,
} as any)
const BpmnRoute = BpmnRouteImport.update({
  id: "/bpmn",
  path: "/bpmn",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: "/tasks/",
  path: "/tasks/",
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: "/jobs/",
  path: "/jobs/",
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIndexRoute = InstancesIndexRouteImport.update({
  id: "/instances/",
  path: "/instances/",
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityIndexRoute = IdentityIndexRouteImport.update({
  id: "/identity/",
  path: "/identity/",
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: "/history/",
  path: "/history/",
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: "/events/",
  path: "/events/",
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: "/deployments/",
  path: "/deployments/",
  getParentRoute: () => rootRouteImport,
} as any)
const DefinitionsIndexRoute = DefinitionsIndexRouteImport.update({
  id: "/definitions/",
  path: "/definitions/",
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsIndexRoute = DecisionsIndexRouteImport.update({
  id: "/decisions/",
  path: "/decisions/",
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: "/batches/",
  path: "/batches/",
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: "/tasks/$id",
  path: "/tasks/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIdRoute = InstancesIdRouteImport.update({
  id: "/instances/$id",
  path: "/instances/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIdRoute = DeploymentsIdRouteImport.update({
  id: "/deployments/$id",
  path: "/deployments/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const DefinitionsIdRoute = DefinitionsIdRouteImport.update({
  id: "/definitions/$id",
  path: "/definitions/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsKeyRoute = DecisionsKeyRouteImport.update({
  id: "/decisions/$key",
  path: "/decisions/$key",
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIdRoute = BatchesIdRouteImport.update({
  id: "/batches/$id",
  path: "/batches/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityUsersIdRoute = IdentityUsersIdRouteImport.update({
  id: "/identity/users/$id",
  path: "/identity/users/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityGroupsIdRoute = IdentityGroupsIdRouteImport.update({
  id: "/identity/groups/$id",
  path: "/identity/groups/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/bpmn": typeof BpmnRoute
  "/dmn": typeof DmnRoute
  "/tenants": typeof TenantsRoute
  "/batches/$id": typeof BatchesIdRoute
  "/decisions/$key": typeof DecisionsKeyRoute
  "/definitions/$id": typeof DefinitionsIdRoute
  "/deployments/$id": typeof DeploymentsIdRoute
  "/instances/$id": typeof InstancesIdRoute
  "/tasks/$id": typeof TasksIdRoute
  "/batches/": typeof BatchesIndexRoute
  "/decisions/": typeof DecisionsIndexRoute
  "/definitions/": typeof DefinitionsIndexRoute
  "/deployments/": typeof DeploymentsIndexRoute
  "/events/": typeof EventsIndexRoute
  "/history/": typeof HistoryIndexRoute
  "/identity/": typeof IdentityIndexRoute
  "/instances/": typeof InstancesIndexRoute
  "/jobs/": typeof JobsIndexRoute
  "/tasks/": typeof TasksIndexRoute
  "/identity/groups/$id": typeof IdentityGroupsIdRoute
  "/identity/users/$id": typeof IdentityUsersIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/bpmn": typeof BpmnRoute
  "/dmn": typeof DmnRoute
  "/tenants": typeof TenantsRoute
  "/batches/$id": typeof BatchesIdRoute
  "/decisions/$key": typeof DecisionsKeyRoute
  "/definitions/$id": typeof DefinitionsIdRoute
  "/deployments/$id": typeof DeploymentsIdRoute
  "/instances/$id": typeof InstancesIdRoute
  "/tasks/$id": typeof TasksIdRoute
  "/batches": typeof BatchesIndexRoute
  "/decisions": typeof DecisionsIndexRoute
  "/definitions": typeof DefinitionsIndexRoute
  "/deployments": typeof DeploymentsIndexRoute
  "/events": typeof EventsIndexRoute
  "/history": typeof HistoryIndexRoute
  "/identity": typeof IdentityIndexRoute
  "/instances": typeof InstancesIndexRoute
  "/jobs": typeof JobsIndexRoute
  "/tasks": typeof TasksIndexRoute
  "/identity/groups/$id": typeof IdentityGroupsIdRoute
  "/identity/users/$id": typeof IdentityUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/bpmn": typeof BpmnRoute
  "/dmn": typeof DmnRoute
  "/tenants": typeof TenantsRoute
  "/batches/$id": typeof BatchesIdRoute
  "/decisions/$key": typeof DecisionsKeyRoute
  "/definitions/$id": typeof DefinitionsIdRoute
  "/deployments/$id": typeof DeploymentsIdRoute
  "/instances/$id": typeof InstancesIdRoute
  "/tasks/$id": typeof TasksIdRoute
  "/batches/": typeof BatchesIndexRoute
  "/decisions/": typeof DecisionsIndexRoute
  "/definitions/": typeof DefinitionsIndexRoute
  "/deployments/": typeof DeploymentsIndexRoute
  "/events/": typeof EventsIndexRoute
  "/history/": typeof HistoryIndexRoute
  "/identity/": typeof IdentityIndexRoute
  "/instances/": typeof InstancesIndexRoute
  "/jobs/": typeof JobsIndexRoute
  "/tasks/": typeof TasksIndexRoute
  "/identity/groups/$id": typeof IdentityGroupsIdRoute
  "/identity/users/$id": typeof IdentityUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/bpmn"
    | "/dmn"
    | "/tenants"
    | "/batches/$id"
    | "/decisions/$key"
    | "/definitions/$id"
    | "/deployments/$id"
    | "/instances/$id"
    | "/tasks/$id"
    | "/batches/"
    | "/decisions/"
    | "/definitions/"
    | "/deployments/"
    | "/events/"
    | "/history/"
    | "/identity/"
    | "/instances/"
    | "/jobs/"
    | "/tasks/"
    | "/identity/groups/$id"
    | "/identity/users/$id"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/bpmn"
    | "/dmn"
    | "/tenants"
    | "/batches/$id"
    | "/decisions/$key"
    | "/definitions/$id"
    | "/deployments/$id"
    | "/instances/$id"
    | "/tasks/$id"
    | "/batches"
    | "/decisions"
    | "/definitions"
    | "/deployments"
    | "/events"
    | "/history"
    | "/identity"
    | "/instances"
    | "/jobs"
    | "/tasks"
    | "/identity/groups/$id"
    | "/identity/users/$id"
  id:
    | "__root__"
    | "/"
    | "/bpmn"
    | "/dmn"
    | "/tenants"
    | "/batches/$id"
    | "/decisions/$key"
    | "/definitions/$id"
    | "/deployments/$id"
    | "/instances/$id"
    | "/tasks/$id"
    | "/batches/"
    | "/decisions/"
    | "/definitions/"
    | "/deployments/"
    | "/events/"
    | "/history/"
    | "/identity/"
    | "/instances/"
    | "/jobs/"
    | "/tasks/"
    | "/identity/groups/$id"
    | "/identity/users/$id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BpmnRoute: typeof BpmnRoute
  DmnRoute: typeof DmnRoute
  TenantsRoute: typeof TenantsRoute
  BatchesIdRoute: typeof BatchesIdRoute
  DecisionsKeyRoute: typeof DecisionsKeyRoute
  DefinitionsIdRoute: typeof DefinitionsIdRoute
  DeploymentsIdRoute: typeof DeploymentsIdRoute
  InstancesIdRoute: typeof InstancesIdRoute
  TasksIdRoute: typeof TasksIdRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
  DecisionsIndexRoute: typeof DecisionsIndexRoute
  DefinitionsIndexRoute: typeof DefinitionsIndexRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  IdentityIndexRoute: typeof IdentityIndexRoute
  InstancesIndexRoute: typeof InstancesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  IdentityGroupsIdRoute: typeof IdentityGroupsIdRoute
  IdentityUsersIdRoute: typeof IdentityUsersIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tenants": {
      id: "/tenants"
      path: "/tenants"
      fullPath: "/tenants"
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dmn": {
      id: "/dmn"
      path: "/dmn"
      fullPath: "/dmn"
      preLoaderRoute: typeof DmnRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bpmn": {
      id: "/bpmn"
      path: "/bpmn"
      fullPath: "/bpmn"
      preLoaderRoute: typeof BpmnRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tasks/": {
      id: "/tasks/"
      path: "/tasks"
      fullPath: "/tasks/"
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/jobs/": {
      id: "/jobs/"
      path: "/jobs"
      fullPath: "/jobs/"
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/instances/": {
      id: "/instances/"
      path: "/instances"
      fullPath: "/instances/"
      preLoaderRoute: typeof InstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/identity/": {
      id: "/identity/"
      path: "/identity"
      fullPath: "/identity/"
      preLoaderRoute: typeof IdentityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/history/": {
      id: "/history/"
      path: "/history"
      fullPath: "/history/"
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/events/": {
      id: "/events/"
      path: "/events"
      fullPath: "/events/"
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/deployments/": {
      id: "/deployments/"
      path: "/deployments"
      fullPath: "/deployments/"
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/definitions/": {
      id: "/definitions/"
      path: "/definitions"
      fullPath: "/definitions/"
      preLoaderRoute: typeof DefinitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decisions/": {
      id: "/decisions/"
      path: "/decisions"
      fullPath: "/decisions/"
      preLoaderRoute: typeof DecisionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/batches/": {
      id: "/batches/"
      path: "/batches"
      fullPath: "/batches/"
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tasks/$id": {
      id: "/tasks/$id"
      path: "/tasks/$id"
      fullPath: "/tasks/$id"
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/instances/$id": {
      id: "/instances/$id"
      path: "/instances/$id"
      fullPath: "/instances/$id"
      preLoaderRoute: typeof InstancesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/deployments/$id": {
      id: "/deployments/$id"
      path: "/deployments/$id"
      fullPath: "/deployments/$id"
      preLoaderRoute: typeof DeploymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/definitions/$id": {
      id: "/definitions/$id"
      path: "/definitions/$id"
      fullPath: "/definitions/$id"
      preLoaderRoute: typeof DefinitionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decisions/$key": {
      id: "/decisions/$key"
      path: "/decisions/$key"
      fullPath: "/decisions/$key"
      preLoaderRoute: typeof DecisionsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/batches/$id": {
      id: "/batches/$id"
      path: "/batches/$id"
      fullPath: "/batches/$id"
      preLoaderRoute: typeof BatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/identity/users/$id": {
      id: "/identity/users/$id"
      path: "/identity/users/$id"
      fullPath: "/identity/users/$id"
      preLoaderRoute: typeof IdentityUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/identity/groups/$id": {
      id: "/identity/groups/$id"
      path: "/identity/groups/$id"
      fullPath: "/identity/groups/$id"
      preLoaderRoute: typeof IdentityGroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BpmnRoute: BpmnRoute,
  DmnRoute: DmnRoute,
  TenantsRoute: TenantsRoute,
  BatchesIdRoute: BatchesIdRoute,
  DecisionsKeyRoute: DecisionsKeyRoute,
  DefinitionsIdRoute: DefinitionsIdRoute,
  DeploymentsIdRoute: DeploymentsIdRoute,
  InstancesIdRoute: InstancesIdRoute,
  TasksIdRoute: TasksIdRoute,
  BatchesIndexRoute: BatchesIndexRoute,
  DecisionsIndexRoute: DecisionsIndexRoute,
  DefinitionsIndexRoute: DefinitionsIndexRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  IdentityIndexRoute: IdentityIndexRoute,
  InstancesIndexRoute: InstancesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  IdentityGroupsIdRoute: IdentityGroupsIdRoute,
  IdentityUsersIdRoute: IdentityUsersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
