/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as JobsRouteImport } from "./routes/jobs"
import { Route as DmnRouteImport } from "./routes/dmn"
import { Route as BpmnRouteImport } from "./routes/bpmn"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TasksIndexRouteImport } from "./routes/tasks/index"
import { Route as InstancesIndexRouteImport } from "./routes/instances/index"
import { Route as DeploymentsIndexRouteImport } from "./routes/deployments/index"
import { Route as DefinitionsIndexRouteImport } from "./routes/definitions/index"
import { Route as TasksIdRouteImport } from "./routes/tasks/$id"
import { Route as InstancesIdRouteImport } from "./routes/instances/$id"
import { Route as DeploymentsIdRouteImport } from "./routes/deployments/$id"
import { Route as DefinitionsIdRouteImport } from "./routes/definitions/$id"

const JobsRoute = JobsRouteImport.update({
  id: "/jobs",
  path: "/jobs",
  getParentRoute: () => rootRouteImport,
} as any)
const DmnRoute = DmnRouteImport.update({
  id: "/dmn",
  path: "/dmn",
  getParentRoute: () => rootRouteImport,
} as any)
const BpmnRoute = BpmnRouteImport.update({
  id: "/bpmn",
  path: "/bpmn",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: "/tasks/",
  path: "/tasks/",
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIndexRoute = InstancesIndexRouteImport.update({
  id: "/instances/",
  path: "/instances/",
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: "/deployments/",
  path: "/deployments/",
  getParentRoute: () => rootRouteImport,
} as any)
const DefinitionsIndexRoute = DefinitionsIndexRouteImport.update({
  id: "/definitions/",
  path: "/definitions/",
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: "/tasks/$id",
  path: "/tasks/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIdRoute = InstancesIdRouteImport.update({
  id: "/instances/$id",
  path: "/instances/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIdRoute = DeploymentsIdRouteImport.update({
  id: "/deployments/$id",
  path: "/deployments/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const DefinitionsIdRoute = DefinitionsIdRouteImport.update({
  id: "/definitions/$id",
  path: "/definitions/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/bpmn": typeof BpmnRoute
  "/dmn": typeof DmnRoute
  "/jobs": typeof JobsRoute
  "/definitions/$id": typeof DefinitionsIdRoute
  "/deployments/$id": typeof DeploymentsIdRoute
  "/instances/$id": typeof InstancesIdRoute
  "/tasks/$id": typeof TasksIdRoute
  "/definitions/": typeof DefinitionsIndexRoute
  "/deployments/": typeof DeploymentsIndexRoute
  "/instances/": typeof InstancesIndexRoute
  "/tasks/": typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/bpmn": typeof BpmnRoute
  "/dmn": typeof DmnRoute
  "/jobs": typeof JobsRoute
  "/definitions/$id": typeof DefinitionsIdRoute
  "/deployments/$id": typeof DeploymentsIdRoute
  "/instances/$id": typeof InstancesIdRoute
  "/tasks/$id": typeof TasksIdRoute
  "/definitions": typeof DefinitionsIndexRoute
  "/deployments": typeof DeploymentsIndexRoute
  "/instances": typeof InstancesIndexRoute
  "/tasks": typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/bpmn": typeof BpmnRoute
  "/dmn": typeof DmnRoute
  "/jobs": typeof JobsRoute
  "/definitions/$id": typeof DefinitionsIdRoute
  "/deployments/$id": typeof DeploymentsIdRoute
  "/instances/$id": typeof InstancesIdRoute
  "/tasks/$id": typeof TasksIdRoute
  "/definitions/": typeof DefinitionsIndexRoute
  "/deployments/": typeof DeploymentsIndexRoute
  "/instances/": typeof InstancesIndexRoute
  "/tasks/": typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/bpmn"
    | "/dmn"
    | "/jobs"
    | "/definitions/$id"
    | "/deployments/$id"
    | "/instances/$id"
    | "/tasks/$id"
    | "/definitions/"
    | "/deployments/"
    | "/instances/"
    | "/tasks/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/bpmn"
    | "/dmn"
    | "/jobs"
    | "/definitions/$id"
    | "/deployments/$id"
    | "/instances/$id"
    | "/tasks/$id"
    | "/definitions"
    | "/deployments"
    | "/instances"
    | "/tasks"
  id:
    | "__root__"
    | "/"
    | "/bpmn"
    | "/dmn"
    | "/jobs"
    | "/definitions/$id"
    | "/deployments/$id"
    | "/instances/$id"
    | "/tasks/$id"
    | "/definitions/"
    | "/deployments/"
    | "/instances/"
    | "/tasks/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BpmnRoute: typeof BpmnRoute
  DmnRoute: typeof DmnRoute
  JobsRoute: typeof JobsRoute
  DefinitionsIdRoute: typeof DefinitionsIdRoute
  DeploymentsIdRoute: typeof DeploymentsIdRoute
  InstancesIdRoute: typeof InstancesIdRoute
  TasksIdRoute: typeof TasksIdRoute
  DefinitionsIndexRoute: typeof DefinitionsIndexRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  InstancesIndexRoute: typeof InstancesIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/jobs": {
      id: "/jobs"
      path: "/jobs"
      fullPath: "/jobs"
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dmn": {
      id: "/dmn"
      path: "/dmn"
      fullPath: "/dmn"
      preLoaderRoute: typeof DmnRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bpmn": {
      id: "/bpmn"
      path: "/bpmn"
      fullPath: "/bpmn"
      preLoaderRoute: typeof BpmnRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tasks/": {
      id: "/tasks/"
      path: "/tasks"
      fullPath: "/tasks/"
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/instances/": {
      id: "/instances/"
      path: "/instances"
      fullPath: "/instances/"
      preLoaderRoute: typeof InstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/deployments/": {
      id: "/deployments/"
      path: "/deployments"
      fullPath: "/deployments/"
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/definitions/": {
      id: "/definitions/"
      path: "/definitions"
      fullPath: "/definitions/"
      preLoaderRoute: typeof DefinitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tasks/$id": {
      id: "/tasks/$id"
      path: "/tasks/$id"
      fullPath: "/tasks/$id"
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/instances/$id": {
      id: "/instances/$id"
      path: "/instances/$id"
      fullPath: "/instances/$id"
      preLoaderRoute: typeof InstancesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/deployments/$id": {
      id: "/deployments/$id"
      path: "/deployments/$id"
      fullPath: "/deployments/$id"
      preLoaderRoute: typeof DeploymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/definitions/$id": {
      id: "/definitions/$id"
      path: "/definitions/$id"
      fullPath: "/definitions/$id"
      preLoaderRoute: typeof DefinitionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BpmnRoute: BpmnRoute,
  DmnRoute: DmnRoute,
  JobsRoute: JobsRoute,
  DefinitionsIdRoute: DefinitionsIdRoute,
  DeploymentsIdRoute: DeploymentsIdRoute,
  InstancesIdRoute: InstancesIdRoute,
  TasksIdRoute: TasksIdRoute,
  DefinitionsIndexRoute: DefinitionsIndexRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  InstancesIndexRoute: InstancesIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
